merge with deploy

diff --git a/.github/workflows/deploy-testing.yaml b/.github/workflows/deploy-testing.yaml
--- a/.github/workflows/deploy-testing.yaml
+++ b/.github/workflows/deploy-testing.yaml
@@ -6,46 +6,129 @@ on:
       - testing
 
 jobs:
-  deploy:
+  setup-php:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
       - name: Laravel initializer
         uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
         with:
           php-version: '7.4'
-
       - name: Copy .env
-        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
-
+        run: php -r "unlink('.env') || copy('.env.testing', '.env');"
+      - name: Verify composer.json
+        run: test -f composer.json || { echo "composer.json not found"; exit 1; }
       - name: Install Dependencies with Composer
-        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+        run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: artifactARv2
+          path: ./
+          overwrite: true
 
+  setup-node:
+    runs-on: ubuntu-latest
+    needs: setup-php
+    steps:
+      - name: Download Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: artifactARv2
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '18'
-
       - name: Install npm Dependencies with Node.js
         run: npm install --legacy-peer-deps
-
       - name: Build Assets
         run: npm run development
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: artifactARv2
+          path: ./
+          overwrite: true
 
+  deploy-code:
+    runs-on: ubuntu-latest
+    needs: setup-node
+    steps:
+      - name: Download Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: artifactARv2
       - name: Deploy to cPanel
         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
         with:
           server: ftp.armgp.org  # ${{ secrets.FTP_SERVER }}
           username: userarmgp # ${{ secrets.FTP_USERNAME }}
           password: TGA&7f&a.@y.wF@*#] # ${{ secrets.FTP_PASSWORD }}
-          protocol: ftps
+          protocol: ftp
           server-dir: /public_html/qa/ # Directorio en el servidor cPanel
-          # Para excluir archivos o directorios del despliegue
           exclude: |
             **/.git*
             **/.git*/**
             **/node_modules*/**
-          # **/vendor*/**
+            **/vendor*/**
+          timeout: 60000
+          port: 21
+#      - name: Upload Artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: artifactARv2
+#          path: ./
+#          overwrite: true
+
+#  deploy-vendor:
+#    runs-on: ubuntu-latest
+#    needs: deploy-code
+#    steps:
+#      - name: Download Artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: artifactARv2
+#      - name: Deploy to cPanel
+#        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
+#        with:
+#          server: ftp.armgp.org  # ${{ secrets.FTP_SERVER }}
+#          username: userarmgp # ${{ secrets.FTP_USERNAME }}
+#          password: TGA&7f&a.@y.wF@*#] # ${{ secrets.FTP_PASSWORD }}
+#          protocol: ftp
+#          server-dir: /public_html/dev/ # Directorio en el servidor cPanel
+#          exclude: |
+#            *
+#            !vendor/
+#            !vendor/**
+#          timeout: 60000
+#          port: 21
+#      - name: Upload Artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: artifactARv2
+#          path: ./
+#          overwrite: true
+#
+#  deploy-node-modules:
+#    runs-on: ubuntu-latest
+#    needs: deploy-vendor
+#    steps:
+#      - name: Download Artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: artifactARv2
+#      - name: Deploy to cPanel
+#        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
+#        with:
+#          server: ftp.armgp.org  # ${{ secrets.FTP_SERVER }}
+#          username: userarmgp # ${{ secrets.FTP_USERNAME }}
+#          password: TGA&7f&a.@y.wF@*#] # ${{ secrets.FTP_PASSWORD }}
+#          protocol: ftp
+#          server-dir: /public_html/dev/ # Directorio en el servidor cPanel
+#          exclude: |
+#            *
+#            !node_modules/
+#            !node_modules/**
+#          timeout: 60000
+#          port: 21
